---
debug: True

database:
  user: trie
  password: trie
  host: localhost
  port: 5432
  name: trie_development

sendgrid:
  api_key: dev-fake-api-key
  default_from: support@totestore.com
  internal_new_order_to: orders@totestore.com

# TODO: Change to live keys.
stripe:
  secret_key: sk_test_Bi7qQ8cy3M4q730QLc6cqZN3
  publishable_key: pk_test_SSTmhE8aocfnGsmEZrN9SEAM

secret_key: trie

security:
  internal_auth_keys:
    test: INTERNAL_AUTH_TOKEN
  internal_auth_tokens:
    test: tote-auth
  token_authentication_key: auth_token
  token_authentication_header: Authentication-Token
  token_max_age: 2592000  # 30 days

roles:
  default_role: member

domain: 127.0.0.1:5000
