---
debug: False


# TODO: Remove secrets.
database:
  user: jktdjieygaqjnj
  password: 6V52dBX3zIZ4xAbgAknm678QyN
  host: ec2-54-243-249-149.compute-1.amazonaws.com
  port: 5432
  name: da979srdtd0d00
