---
debug: False

email:
  username:
  password:
  default_sender: no-reply@totestore.com
  debug: False

# TODO: Remove api key.
sendgrid:
  api_key:
  default_from:
  internal_new_order_to:

# TODO: Remove secret key. And stop using the test keys.
stripe:
  secret_key:
  publishable_key:

# TODO: Remove secrets
secret_key:

security:
  internal_auth_keys: {}
  internal_auth_tokens: {}
  token_authentication_key: auth_token
  token_authentication_header: Authentication-Token
  token_max_age: 2592000  # 30 days

roles:
  default_role: member

domain:
