---
debug: False

email:
  username: admin@totestore.com
  password: xGpb74NqrQrqBq#wnKAUzsFQ
  default_sender: no-reply@totestore.com

# TODO: Remove api key.
sendgrid:
  api_key: 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
  default_from: support@totestore.com
  internal_new_order_to: orders@totestore.com

# TODO: Remove secret key. And stop using the test keys.
stripe:
  secret_key: sk_test_Bi7qQ8cy3M4q730QLc6cqZN3
  publishable_key: pk_test_SSTmhE8aocfnGsmEZrN9SEAM
  # secret_key: sk_live_SDUVqQEfhKTNCXUKajB59NKO
  # publishable_key: pk_live_InorHF5F9AWzp1UuBM8Xz41b

# TODO: Remove secrets
secret_key: jhbVYTgyvgHUByg6745SJs67s6GVC7dcsbd8

security:
  internal_auth_keys: {}
  internal_auth_tokens: {}
  token_authentication_key: auth_token
  token_authentication_header: Authentication-Token
  token_max_age: 2592000  # 30 days

roles:
  default_role: member

domain: https://www.totestore.com
