---
debug: False

# TODO: Remove api key.
sendgrid:
  api_key: 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
  default_from: support@totestore.com
  internal_new_order_to: orders@totestore.com

# TODO: Remove secret key.
stripe:
  secret_key: sk_live_SDUVqQEfhKTNCXUKajB59NKO
  publishable_key: pk_live_InorHF5F9AWzp1UuBM8Xz41b

# TODO: Remove secrets
secret_key: jhbVYTgyvgHUByg6745SJs67s6GVC7dcsbd8
