---
debug: True

database:
  user: trie
  password: trie
  host: localhost
  port: 5432
  name: trie_test

sendgrid:
  api_key: test_sendgrid_api_key
  default_from: support@totestore.com
  internal_new_order_to: orders@totestore.com

stripe:
  secret_key: stripe_secret_key
  publishable_key: stripe_publishable_key

secret_key: trie

security:
  internal_auth_keys:
    test: INTERNAL_AUTH_TOKEN
  internal_auth_tokens:
    test: tote-auth

roles:
  default_role: member

domain: 127.0.0.1:5000
