---
debug: True

database:
  user: trie
  password: trie
  host: localhost
  port: 5432
  name: trie_test

sendgrid:
  api_key: test_sendgrid_api_key
  default_from: support@totestore.com

stripe:
  secret_key: stripe_secret_key
  publishable_key: stripe_publishable_key

secret_key: trie
